services:
    romantymoshyk.unobtrusive_validation_extension:
        class: RomanTymoshyk\UnobtrusiveValidationBundle\Form\Extension\UnobtrusiveValidationExtension
        tags:
            - { name: form.type_extension, extended_type: Symfony\Component\Form\Extension\Core\Type\FormType }
        calls:
            - [setTranslator, ['@translator']]
